[package]
name = "wascc-redis"
version = "0.8.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"
homepage = "https://wascc.dev"
repository = "https://github.com/wascc/redis-provider"
description = "Redis capability provider for the waSCC wasm host runtime"
license = "Apache-2.0"
documentation = "https://docs.rs/wascc-redis"
readme = "README.md"
keywords = ["webassembly", "wasm", "wasi", "wascc", "redis"]
categories = ["wasm", "api-bindings"]

[badges]
maintenance = { status = "actively-developed" }

[features]
# Enable if the provider will be statically compiled into a host
static_plugin = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
env_logger = "0.7.1"
lazy_static = "1.4.0"
crossbeam-channel = "0.4.2"
crossbeam = "0.7.3"
crossbeam-utils = "0.7.2"
log = "0.4.8"
wascc-codec = "0.8.0"
redis = "0.16.0"
